config/routes.rb
WellB2B::Application.routes.draw do
  resources :users, :user_sessions

  resources :challenges
    
  match 'login' => 'user_sessions#new', :as => :login
  match 'logout' => 'user_sessions#destroy', :as => :logout
  

   match 'challenges/list/my_challenges' => 'challenges#my_challenges'
   match 'challenges/list/sent_challenges' => 'challenges#sent_challenges'

   root :to => 'user_sessions#new'
  

end

app/models/challenge.rb
class Challenge < ActiveRecord::Base
  attr_accessible :user_from_id, :user_to_id, :challenge_txt, :challenge_tm, :send_dt, :accepted, :accepted_dt, :due_dt, :complete_dt
end

app/models/user.rb
class User < ActiveRecord::Base
  acts_as_authentic
end

app/models/user_session.rb
class UserSession < Authlogic::Session::Base
  def to_key
     new_record? ? nil : [ self.send(self.class.primary_key) ]
  end
  
  def persisted?
    false
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  
  helper_method :current_user
  
  private
  
  def current_user_session
    return @current_user_session if defined?(@current_user_session)
    @current_user_session = UserSession.find
  end
  
  def current_user
    return @current_user if defined?(@current_user)
    @current_user = current_user_session && current_user_session.record
  end
end

app/controllers/challenges_controller.rb
class ChallengesController < ApplicationController
  def index
    if current_user.nil?
      redirect_to :controller=>'user_sessions', :action => 'new';
    end
    @challenges = [];#Challenge.find_all_by_user_from_id(current_user.id)
  end

  def show
    @challenge = Challenge.find(params[:id])
  end

  def new
    @challenge = Challenge.new
  end

  def create
    @challenge = Challenge.new(params[:challenge])
    @challenge[:user_from_id] = current_user.id
    @challenge[:complete_dt] = nil;
    @challenge[:accepted_dt] = nil;
    if @challenge.save     
      #render :action => "sent_challenges", :object => @challenges
      #redirect_to :action => "sent_challenges"
      #redirect_to @challenge, :notice => "Successfully created challenge."
      render :action => 'sent_challenges'
    else
      render :action => 'new'
    end
  end

  def edit
    @challenge = Challenge.find(params[:id])
  end

  def update
    @challenge = Challenge.find(params[:id])
    
    if @challenge.update_attributes(params[:challenge])
      redirect_to @challenge
    else
      render :action => 'edit'
    end
  end
  
  def my_challenges
    #@challenges = Challenge.find_all_by_user_to_id(current_user.id)
    respond_to do |format|
      format.html # 
     # format.xml { render :xml => @user_session }
    end
     # render 'my_challenges';
  end
  
  def sent_challenges
    #@challenges = Challenge.find_all_by_user_from_id(current_user.id)
    respond_to do |format|
      format.html # 
     # format.xml { render :xml => @user_session }
    end
     # render 'my_challenges';
  end
  
  

  def destroy
    @challenge = Challenge.find(params[:id])
    @challenge.destroy
    redirect_to challenges_url, :notice => "Successfully destroyed challenge."
  end
end

app/controllers/user_sessions_controller.rb
class UserSessionsController < ApplicationController

  # GET /user_sessions/new
  # GET /user_sessions/new.xml
  def new
    @user_session = UserSession.new

    respond_to do |format|
      format.html # { redirect_to(:challenges) }# new.html.erb
      format.xml { render :xml => @user_session }
    end
  end

  # POST /user_sessions
  # POST /user_sessions.xml
  def create
    @user_session = UserSession.new(params[:user_session])

    respond_to do |format|
      if @user_session.save
        #format.html { redirect_to("/users/#{current_user.id}/my_challenges", :notice => 'Login Successful') }
        #format.html { redirect_to(:controller => :challenges, :action => :sent_challenges) }
        format.html { redirect_to("/challenges/list/my_challenges") }
        
        format.xml { render :xml => @user_session, :status => :created, :location => @user_session }
      else
        format.html { render :action => "new" }
        format.xml { render :xml => @user_session.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /user_sessions/1
  # DELETE /user_sessions/1.xml
  def destroy
    @user_session = UserSession.find
    @user_session.destroy

    respond_to do |format|
      format.html { redirect_to(login_path) } # #{ redirect_to(:users, :notice => 'Goodbye!') }
      format.xml { head :ok }
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # GET /users
  # GET /users.xml
  def index
    @users = User.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @users }
    end
  end

  # GET /users/1
  # GET /users/1.xml
  def show
    @user = User.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @user }
    end
  end

  # GET /users/new
  # GET /users/new.xml
  def new
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @user }
    end
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # POST /users
  # POST /users.xml
  def create
    @user = User.new(params[:user])

    respond_to do |format|
      if @user.save
        #format.html { redirect_to(@user, :notice => 'User was successfully created.') }
        format.html { redirect_to("/challenges/list/my_challenges") }
        format.xml  { render :xml => @user, :status => :created, :location => @user }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @user.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /users/1
  # PUT /users/1.xml
  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to(@user, :notice => 'User was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @user.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.xml
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to(users_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/challenges_helper.rb
module ChallengesHelper
end

app/helpers/error_messages_helper.rb
module ErrorMessagesHelper
  # Render error messages for the given objects. The :message and :header_message options are allowed.
  def error_messages_for(*objects)
    options = objects.extract_options!
    options[:header_message] ||= I18n.t(:"activerecord.errors.header", :default => "Invalid Fields")
    options[:message] ||= I18n.t(:"activerecord.errors.message", :default => "Correct the following errors and try again.")
    messages = objects.compact.map { |o| o.errors.full_messages }.flatten
    unless messages.empty?
      content_tag(:div, :class => "error_messages") do
        list_items = messages.map { |msg| content_tag(:li, msg) }
        content_tag(:h2, options[:header_message]) + content_tag(:p, options[:message]) + content_tag(:ul, list_items.join.html_safe)
      end
    end
  end

  module FormBuilderAdditions
    def error_messages(options = {})
      @template.error_messages_for(@object, options)
    end
  end
end

ActionView::Helpers::FormBuilder.send(:include, ErrorMessagesHelper::FormBuilderAdditions)

app/helpers/layout_helper.rb
# These helper methods can be called in your template to set variables to be used in the layout
# This module should be included in all views globally,
# to do so you may need to add this line to your ApplicationController
#   helper :layout
module LayoutHelper
  def title(page_title, show_title = true)
    content_for(:title) { h(page_title.to_s) }
    @show_title = show_title
  end

  def show_title?
    @show_title
  end

  def stylesheet(*args)
    content_for(:head) { stylesheet_link_tag(*args) }
  end

  def javascript(*args)
    content_for(:head) { javascript_include_tag(*args) }
  end
end

app/helpers/user_sessions_helper.rb
module UserSessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/challenges/_form.html.erb
<%= form_for @challenge do |f| %>
  <%= f.error_messages %>
  <!-- <p> -->
	<%= f.hidden_field(:user_from_id, :value => current_user.id) %>
    <%#= f.label :user_from_id %><br />
    <%#= f.text_field :user_from_id %>
  <!-- </p> -->
  <!-- <p> -->
    <%#= f.label :user_to_id %><br />
    <%#= f.text_field :user_to_id %>
  <!-- </p> -->
  <p>
	Challenge User:
	<%= f.collection_select :user_to_id, User.all, :id, :username %>
  </p>
  <p>
    Challenge Description:
    <%= f.text_field :challenge_txt %>
  </p>
  <p>
    Note: Challenge currently defaults to 5 minutes.
  <!-- <p> -->
    <%#= f.label :challenge_tm %><br />
    <%#= f.text_field :challenge_tm %>
  <!-- </p> -->
  <!-- <p> -->
    <%#= f.label :send_dt %><br />
    <%#= f.date_select :send_dt %>
  <!-- </p> -->
  <!-- <p> -->
    <%#= f.label :accepted %><br />
    <%#= f.text_field :accepted %>
  <!-- </p> -->
  <!-- <p> -->
    <%#= f.label :accepted_dt %><br />
    <%#= f.date_select :accepted_dt %>
  <!-- </p> -->
  <!-- <p> -->
    <%#= f.label :due_dt %><br />
    <%#= f.date_select :due_dt %>
  <!-- </p> -->
  <!-- <p> -->
    <%#= f.label :complete_dt %><br />
    <%#= f.date_select :complete_dt %>
  <!-- </p> -->
  <p><%= f.submit %></p>
<% end %>

app/views/challenges/edit.html.erb
<% title "Edit Challenge" %>

<%= render 'form' %>

<p>
  <%= link_to "Show", @challenge %> |
  <%= link_to "View All", challenges_path %>
</p>

app/views/challenges/index.html.erb
<% title "Challenges" %>

<table>
  <tr>
    <th>From</th>
    <th>Description</th>
    <th>Complete Time</th>
    <th>Send Date</th>
    <th>Accept Date</th>
    <th>Due</th>
    <th>Complete Time</th>
  </tr>
  <% for challenge in @challenges %>
    <tr>
      <td><%= challenge.user_from_id %></td>
      <td><%= challenge.challenge_txt %></td>
      <td><%= challenge.challenge_tm %></td>
      <td><%= challenge.send_dt %></td>
      <td><%= challenge.accepted_dt %></td>
      <td><%= challenge.due_dt %></td>
      <td><%= challenge.complete_dt %></td>
      <td><%= link_to "Show", challenge %></td>
      <td><%= link_to "Edit", edit_challenge_path(challenge) %></td>
      <td><%= link_to "Destroy", challenge, :confirm => 'Are you sure?', :method => :delete %></td>
    </tr>
  <% end %>
</table>

app/views/challenges/my_challenges.html.erb
<% title "My Challenges" %>
<%  @challenges = Challenge.find_all_by_user_to_id(current_user.id, :order => 'created_at DESC') %>

<table>
  <tr>
    <th>From</th>
    <th>Description</th>
    <th>Completed On</th>
	<th>Accepted Date</th>
    <!-- <th>Send Date</th>       
       <th>Due Date</th>
       <th>Complete Date</th> -->
  </tr>
  <% for challenge in @challenges %>
    <tr>
      <td><div style="color:green; font-style:italics;">
			<% if User.exists?(challenge.user_from_id)	
			 user_from = User.find(challenge.user_from_id)%>
		  	<%# if !user_from.nil? %>
		    	<%= user_from.username %>
		  	<% end%>
		  </div>
	  </td>
      <td><%= challenge.challenge_txt %></td>

	  <td>
		<% if challenge.accepted == 1 %>
			<span style="color:orange; font-weight:bold">ACCEPTED!</span>
		<%elsif challenge.accepted == 0 %>
			<span style="color:red; ">Rejected ...<span style="color:red; font-weght:bold; "> Slacker!</span></span>
		<% else %>
			
		<% end %>
		</td>
      <!-- <td><%#= challenge.challenge_tm %></td>
            <td><%#= challenge.send_dt %></td>
            
            <td><%#= challenge.due_dt %></td> -->
      <td><%= challenge.complete_dt %></td>
      <td><%= link_to "Show", challenge %></td>
      <td><%#= link_to "Edit", edit_challenge_path(challenge) %></td>
      <td><%#= link_to "Destroy", challenge, :confirm => 'Are you sure?', :method => :delete %></td>
    </tr>
  <% end %>
</table>

<p><%= link_to "New Challenge", new_challenge_path %></p>

app/views/challenges/new.html.erb
<% title "New Challenge!" %>
Challenge your friend, coworker or yourself!

<%= render 'form' %>

<p><%= link_to "Back to List", challenges_path %></p>

app/views/challenges/sent_challenges.erb
<% title "Sent Challenges" %>

<table>
  <tr>
    <th>User From</th>
    <th>User To</th>
    <th>Challenge Txt</th>
    <th>Challenge Tm</th>
    <th>Send Dt</th>
    <th>Accepted</th>
    <th>Accepted Dt</th>
    <th>Due Dt</th>
    <th>Complete Dt</th>
  </tr>
  <% for challenge in @challenges %>
    <tr>
      <td><%= challenge.user_from_id %></td>
      <td><%= challenge.user_to_id %></td>
      <td><%= challenge.challenge_txt %></td>
      <td><%= challenge.challenge_tm %></td>
      <td><%= challenge.send_dt %></td>
      <td><%= challenge.accepted %></td>
      <td><%= challenge.accepted_dt %></td>
      <td><%= challenge.due_dt %></td>
      <td><%= challenge.complete_dt %></td>
      <td><%= link_to "Show", challenge %></td>
      <td><%= link_to "Edit", edit_challenge_path(challenge) %></td>
      <td><%= link_to "Destroy", challenge, :confirm => 'Are you sure?', :method => :delete %></td>
    </tr>
  <% end %>
</table>

<p><%= link_to "New Challenge", new_challenge_path %></p>

app/views/challenges/sent_challenges.html.erb
<% title "Sent Challenges" %>
<%  @challenges = Challenge.find_all_by_user_from_id(current_user.id, :order => 'created_at DESC') %>
<table>
  <tr>
    <th>To</th>
    <th>Description</th>
    <th>Duration</th>
    <th>Send Date</th>
    <th>Accepted</th>
    <th>Accepted Date</th>
    <th>Due Date</th>
    <th>Complete Date</th>
  </tr>
  <% for challenge in @challenges %>
    <tr>
	      <td>
				<% if User.exists?(challenge.user_to_id)
					user_to = User.find(challenge.user_to_id) %>
			  	<%# if !user_to.nil? %>
			    	<%= user_to.username %>
			  	<% end%>
		  </td>
      <td><%= challenge.challenge_txt %></td>
      <td><%= challenge.challenge_tm %></td>
      <td><%= challenge.send_dt %></td>
      <td><%= challenge.accepted %></td>
      <td><%= challenge.accepted_dt %></td>
      <td><%= challenge.due_dt %></td>
      <td><%= challenge.complete_dt %></td>
      <td><%= link_to "Show", challenge %></td>
      <td><%#= link_to "Edit", edit_challenge_path(challenge) %></td>
      <td><%= link_to "Destroy", challenge, :confirm => 'Are you sure?', :method => :delete %></td>
    </tr>
  <% end %>
</table>

<p><%#= link_to "New Challenge", new_challenge_path %></p>

app/views/challenges/show.html.erb
<% title "Challenge Details" %>
<link type="text/css" rel="stylesheet" href="ex.css?3.2"/>
 <%= javascript_include_tag "protovis-d3.2.js" %>
 <script type="text/javascript+protovis">
 </script>
<p>
  <strong>From:</strong>
  <% user_from = User.find(@challenge.user_from_id)%>
  <% if !user_from.nil? %>
    <%= user_from.username %>
  <% end%>
</p>
<p>
  <strong>To:</strong>
  <% user_to = User.find(@challenge.user_to_id)%>
  <% if !user_to.nil? %>
    <%= user_to.username %>
  <% end%>
</p>
<p>
  <strong>Description:</strong>
  <%= @challenge.challenge_txt %>
</p>
<% if @challenge.accepted.nil?%>
	<%= form_for @challenge do |f| %>
		Reject
		<%= f.radio_button :accepted, 0 %>
		Accept
		<%= f.radio_button :accepted, 1 %>
		<%= f.hidden_field(:accepted_dt, :value => Time.now) %>
		<%= f.submit %>
	<% end %>
<% end %>
<p>
  <strong>Challenge Time:</strong>
  <%= @challenge.challenge_tm %>
</p>
<p>
  <strong>Send Date:</strong>
  <%= @challenge.send_dt %>
</p>
<p>
  <strong>Accepted Date:</strong>
  <%= @challenge.accepted_dt %>
</p>
<p>
  <strong>Due Date:</strong>
  <%= @challenge.due_dt %>
</p>

<% if !@challenge.complete_dt.nil? %>
	<H2>I've done it!!! Hurray!</H2>	
<% else %>
	<% if @challenge.accepted == 1 %> 
		<%if (Time.now - @challenge.updated_at) > 60 %>
			<H4>LOSER!!! LOSER!!! Haaaa!</H4>
		<% else %>
			<%= form_for @challenge do |f| %>
			<%= f.hidden_field(:complete_dt, :value => Time.now) %>
			<%= f.submit 'I have completed it!'%>
			<% end %>
		<% end %>
	<% end %>
<% end %>
<p>
  <strong>Complete Date:</strong>
  <%= @challenge.complete_dt %>
</p>
</p>

<%#= submit_tag(value = "Save changes", options = {}) %>
<p>
  <%= link_to "Edit", edit_challenge_path(@challenge) %> |
  <%= link_to "Destroy", @challenge, :confirm => 'Are you sure?', :method => :delete %> |
  <%= link_to "View All", challenges_path %>
</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
	<div style="float:right; background-color:white;">
		<%#= "Request Action: #{request[:action]}"%>
		<%#= "Request Controller: #{request[:controller]}"%>
		 <% if current_user.nil? %>
	        <%= link_to "Register", new_user_path%>
			<%= link_to "Login", login_path %>
		 <% else %>
			<%= link_to "Logout", logout_path %>
		 <% end %>	
	</div>	
    <title><%= content_for?(:title) ? yield(:title) : "Wellness Buzz" %></title>
    <%= stylesheet_link_tag "application" %>
    <%= javascript_include_tag :defaults %>
    <%= csrf_meta_tag %>
    <%= yield(:head) %>
	
  </head>
  <body>
    <div id="container">
      <img align="right" width="150" height="150" src="/images/B2BWellLogo.png"/>
      <% flash.each do |name, msg| %>
        <%= content_tag :div, msg, :id => "flash_#{name}" %>
      <% end %>
	 <div id = "nav">
		<% if request[:controller] == 'user_sessions' || 
			(request[:controller] == 'users' && request[:action] == 'new')%>
		<% else %>
		    <% if !current_user.nil?%>
				Hello <span style="font-style:italic;color:red;"><%= " #{current_user.username}!"%></span><br/>
			<% end %>		    
     	<div style="text-align:center">
    	    	<%= link_to "[New Challenge]\t", new_challenge_path %>
		    <%= link_to "[My Challenges]\t",  '/challenges/list/my_challenges' %>
		    <%= link_to "[Sent Challenges]",'/challenges/list/sent_challenges' %>
     	</div>
	    <% end %>
	 <div>
      <%= content_tag :h1, yield(:title) if show_title? %>
	  
      <%= yield %>
    </div>
  </body>
</html>

app/views/user_sessions/_form.html.erb
<%= form_for(@user_session) do |f| %>
  <% if @user_session.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user_session.errors.count, "error") %> prohibited this user_session from being saved:</h2>

      <ul>
      <% @user_session.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :username %><br />
    <%= f.text_field :username %>
  </div>
  <div class="field">
    <%= f.label :password %><br />
    <%= f.password_field :password %>
  </div>
  <div class="actions">
    <%= f.submit "Login"%>
  </div>
<% end %>

app/views/user_sessions/edit.html.erb
<h1>Editing user_session</h1>

<%= render 'form' %>

<%= link_to 'Show', @user_session %> |
<%= link_to 'Back', user_sessions_path %>

app/views/user_sessions/index.html.erb
<h1>Listing user_sessions</h1>

<table>
  <tr>
    <th>Username</th>
    <th>Password</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @user_sessions.each do |user_session| %>
  <tr>
    <td><%= user_session.username %></td>
    <td><%= user_session.password %></td>
    <td><%= link_to 'Show', user_session %></td>
    <td><%= link_to 'Edit', edit_user_session_path(user_session) %></td>
    <td><%= link_to 'Destroy', user_session, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'Please Login', new_user_session_path %>

app/views/user_sessions/new.html.erb
<h1>Welcome to B2B Well!</h1>

<%= render 'form' %>

app/views/user_sessions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Username:</b>
  <%= @user_session.username %>
</p>

<p>
  <b>Password:</b>
  <%= @user_session.password %>
</p>


<%= link_to 'Edit', edit_user_session_path(@user_session) %> |
<%= link_to 'Back', user_sessions_path %>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :username %><br />
    <%= f.text_field :username %>
  </div>

  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %><br />
    <%= f.password_field :password %>
  </div>

  <div class="field">
      <%= f.label :password_confirmation %><br />
      <%= f.password_field :password_confirmation %>
  </div>
  
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Listing users</h1>

<table>
  <tr>
    <th>Username</th>
    <th>Email</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @users.each do |user| %>
  <tr>
    <td><%= user.username %></td>
    <td><%= user.email %></td>
    <td><%= link_to 'Show', user %></td>
    <td><%= link_to 'Edit', edit_user_path(user) %></td>
    <td><%= link_to 'Destroy', user, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New User', new_user_path %>

app/views/users/my_challenges.erb
These will be my challenges

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<%#= link_to "New Challenge", new_challenge_path %>
<%#= link_to "My Challenges", :controller => :challenges, :action => :my_challenges, :id => current_user.id %>
<%#= link_to "Sent Challenges", :controller => :challenges, :action => :sent_challenges, :id => current_user.id %>

<p>
  <b>Username:</b>
  <%= @user.username %>
</p>

<p>
  <b>Email:</b>
  <%= @user.email %>
</p>

<p>
  <b>Crypted password:</b>
  <%= @user.crypted_password %>
</p>

<p>
  <b>Password salt:</b>
  <%= @user.password_salt %>
</p>

<p>
  <b>Persistence token:</b>
  <%= @user.persistence_token %>
</p>


<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>